package com.wedding.platform.operations.notification.persistence.entity;

public enum UserNotificationType {
    PROJECT_LINK_APPROVED,
    PROJECT_LINK_REJECTED,
    FEEDBACK_APPROVED,
    FEEDBACK_REJECTED,
    FEEDBACK_OFFLINE,
    PROJECT_REVIEW_TASK,
    COLLECTION_REVIEW_TASK,
    PROJECT_REVIEW_APPROVED,
    PROJECT_REVIEW_REJECTED,
    COLLECTION_REVIEW_APPROVED,
    COLLECTION_REVIEW_REJECTED,
    PROJECT_PARTICIPANT_ADDED,
    PROJECT_PARTICIPANT_REMOVED,
    COLLECTION_PARTICIPANT_ADDED,
    COLLECTION_PARTICIPANT_REMOVED,
    PROJECT_PUBLISHED,
    PROJECT_OFFLINE,
    COLLECTION_PUBLISHED,
    COLLECTION_OFFLINE,
    CUSTOMER_PROJECT_APPLICATION_NEW,
    CUSTOMER_FEEDBACK_NEW,
    FEEDBACK_REPLY_SUBMITTED,
    FEEDBACK_REPLY_APPROVED,
    FEEDBACK_REPLY_REJECTED,
    CONSULTATION_NEW
}
