package com.wedding.platform.operations.notification.persistence.entity;

public enum UserNotificationType {
    LEGACY,
    FEEDBACK_APPROVED,
    FEEDBACK_REJECTED,
    FEEDBACK_OFFLINE,
    COLLECTION_REVIEW_TASK,
    COLLECTION_REVIEW_APPROVED,
    COLLECTION_REVIEW_REJECTED,
    COLLECTION_PARTICIPANT_ADDED,
    COLLECTION_PARTICIPANT_REMOVED,
    COLLECTION_PUBLISHED,
    COLLECTION_OFFLINE,
    CUSTOMER_FEEDBACK_NEW,
    FEEDBACK_REPLY_SUBMITTED,
    FEEDBACK_REPLY_APPROVED,
    FEEDBACK_REPLY_REJECTED,
    CONSULTATION_NEW
}
